"""ReqIF 1.2 export of the system requirements (SYS-052).

ReqIF (OMG Requirements Interchange Format, namespace 20110401) is how requirements move between tools
such as IBM DOORS Next, Jama Connect, Polarion and Capella. Exporting to it means the same requirements
and verification links in docs/02-Requirements.md can be imported into a requirements database.

Each requirement becomes a SPEC-OBJECT with string attributes:
  ReqIF.ForeignID (SYS-xxx), ReqIF.Text, Section, Verification Method, Source, Verified By.
The output is deterministic (a fixed baseline timestamp, requirements in document order), so CI can
check the committed file against a fresh export, the same way it checks docs/RTM.md.
"""

import pathlib
import re
import xml.etree.ElementTree as ET

from . import rtm

NS = "http://www.omg.org/spec/ReqIF/20110401/reqif.xsd"
BASELINE = "2026-09-25T00:00:00Z"
METHODS = {"T": "Test", "A": "Analysis", "I": "Inspection", "D": "Demonstration"}
ATTRS = (  # identifier, long name
    ("ad-id", "ReqIF.ForeignID"),
    ("ad-text", "ReqIF.Text"),
    ("ad-section", "Section"),
    ("ad-method", "Verification Method"),
    ("ad-source", "Source"),
    ("ad-verified", "Verified By"),
)


def _sections(path):
    """Map requirement ID to the '## Heading' it sits under."""
    section, out = "", {}
    for line in pathlib.Path(path).read_text(encoding="utf-8").splitlines():
        if line.startswith("## "):
            section = line[3:].strip()
        m = rtm.REQ_ROW.match(line)
        if m:
            out[m.group(1)] = section
    return out


def _el(parent, tag, text=None, **attrs):
    e = ET.SubElement(parent, f"{{{NS}}}{tag}", {k.replace("_", "-"): v for k, v in attrs.items()})
    if text is not None:
        e.text = text
    return e


def build(root=".", baseline=BASELINE):
    root = pathlib.Path(root)
    req_path = root / "docs" / "02-Requirements.md"
    reqs = rtm.read_requirements(req_path)
    tags = rtm.read_tags(root / "tests")
    sections = _sections(req_path)

    ET.register_namespace("", NS)
    doc = ET.Element(f"{{{NS}}}REQ-IF")
    header = _el(_el(doc, "THE-HEADER"), "REQ-IF-HEADER", IDENTIFIER="hdr-aim")
    _el(header, "COMMENT", "Generated by `python -m aim reqif` from docs/02-Requirements.md and the tests' verifies: tags.")
    _el(header, "CREATION-TIME", baseline)
    _el(header, "REPOSITORY-ID", "https://github.com/ExpertVagabond/adsb-integrity-monitor")
    _el(header, "REQ-IF-TOOL-ID", "adsb-integrity-monitor reqif export")
    _el(header, "REQ-IF-VERSION", "1.0")
    _el(header, "SOURCE-TOOL-ID", "adsb-integrity-monitor")
    _el(header, "TITLE", "ADS-B Integrity Monitor: System Requirements")

    content = _el(_el(doc, "CORE-CONTENT"), "REQ-IF-CONTENT")
    _el(_el(content, "DATATYPES"), "DATATYPE-DEFINITION-STRING",
        IDENTIFIER="dt-string", LAST_CHANGE=baseline, LONG_NAME="String", MAX_LENGTH="4000")

    types = _el(content, "SPEC-TYPES")
    sot = _el(types, "SPEC-OBJECT-TYPE", IDENTIFIER="sot-requirement", LAST_CHANGE=baseline, LONG_NAME="System Requirement")
    spec_attrs = _el(sot, "SPEC-ATTRIBUTES")
    for ident, name in ATTRS:
        ad = _el(spec_attrs, "ATTRIBUTE-DEFINITION-STRING", IDENTIFIER=ident, LAST_CHANGE=baseline, LONG_NAME=name)
        _el(_el(ad, "TYPE"), "DATATYPE-DEFINITION-STRING-REF", "dt-string")
    _el(types, "SPECIFICATION-TYPE", IDENTIFIER="st-requirements", LAST_CHANGE=baseline, LONG_NAME="Requirements Document")

    objects = _el(content, "SPEC-OBJECTS")
    for rid, r in reqs.items():
        obj = _el(objects, "SPEC-OBJECT", IDENTIFIER=rid, LAST_CHANGE=baseline, LONG_NAME=rid)
        values = _el(obj, "VALUES")
        for (ident, _name), value in zip(ATTRS, (rid, r["text"], sections.get(rid, ""), METHODS[r["method"]],
                                                 r["source"], "; ".join(tags.get(rid, [])) or "NOT VERIFIED")):
            av = _el(values, "ATTRIBUTE-VALUE-STRING", THE_VALUE=value)
            _el(_el(av, "DEFINITION"), "ATTRIBUTE-DEFINITION-STRING-REF", ident)
        _el(_el(obj, "TYPE"), "SPEC-OBJECT-TYPE-REF", "sot-requirement")

    spec = _el(_el(content, "SPECIFICATIONS"), "SPECIFICATION",
               IDENTIFIER="spec-system-requirements", LAST_CHANGE=baseline, LONG_NAME="System Requirements")
    _el(_el(spec, "TYPE"), "SPECIFICATION-TYPE-REF", "st-requirements")
    children = _el(spec, "CHILDREN")
    for rid in reqs:
        h = _el(children, "SPEC-HIERARCHY", IDENTIFIER=f"h-{rid}", LAST_CHANGE=baseline)
        _el(_el(h, "OBJECT"), "SPEC-OBJECT-REF", rid)

    ET.indent(doc, space="  ")
    return '<?xml version="1.0" encoding="UTF-8"?>\n' + ET.tostring(doc, encoding="unicode") + "\n", len(reqs)


def write(root=".", out="docs/requirements.reqif"):
    text, n = build(root)
    path = pathlib.Path(root) / out
    path.write_text(text, encoding="utf-8")
    return path, n


def parse_ids(text):
    """Requirement IDs present in an export, in order (used by tests)."""
    return re.findall(r'<SPEC-OBJECT IDENTIFIER="(SYS-\d{3})"', text)
