"""Requirements Traceability Matrix generator (SYS-050).

Reads requirement rows from docs/02-Requirements.md (table rows starting with `| SYS-`)
and `verifies: SYS-xxx` tags from test docstrings/comments, then writes docs/RTM.md.
Exits non-zero if any requirement has no verifying test, or a test cites an unknown ID.
"""

import pathlib
import re

REQ_ROW = re.compile(r"^\|\s*(SYS-\d{3})\s*\|\s*(.+?)\s*\|\s*([TAID])\s*\|\s*(.+?)\s*\|\s*$")
TAG = re.compile(r"verifies:\s*((?:SYS-\d{3}[,\s]*)+)")
TEST_DEF = re.compile(r"^\s*def (test_\w+)")


def read_requirements(path):
    reqs = {}
    for line in pathlib.Path(path).read_text(encoding="utf-8").splitlines():
        m = REQ_ROW.match(line)
        if m:
            rid, text, method, source = m.groups()
            reqs[rid] = {"text": text, "method": method, "source": source}
    return reqs


def read_tags(test_dir):
    """Return {req_id: ["tests/file.py::test_name", ...]}.

    A tag belongs to the nearest preceding `def test_...` in the same file.
    """
    tags = {}
    for f in sorted(pathlib.Path(test_dir).glob("test_*.py")):
        current = None
        for line in f.read_text(encoding="utf-8").splitlines():
            d = TEST_DEF.match(line)
            if d:
                current = d.group(1)
                continue
            m = TAG.search(line)
            if m and current:
                for rid in re.findall(r"SYS-\d{3}", m.group(1)):
                    tags.setdefault(rid, []).append(f"{f.parent.name}/{f.name}::{current}")
    return tags


def build(reqs, tags):
    """Return (markdown, unverified_ids, unknown_ids)."""
    unverified = [r for r in reqs if r not in tags]
    unknown = sorted(t for t in tags if t not in reqs)
    method_name = {"T": "Test", "A": "Analysis", "I": "Inspection", "D": "Demonstration"}
    lines = [
        "# Requirements Traceability Matrix",
        "",
        "Generated by `python -m aim rtm` from docs/02-Requirements.md and the `verifies:` tags in tests/. Do not edit by hand.",
        "",
        f"**{len(reqs) - len(unverified)} of {len(reqs)} requirements verified.**",
        "",
        "| ID | Requirement | Method | Source | Verified by |",
        "|---|---|---|---|---|",
    ]
    for rid, r in reqs.items():
        by = "<br>".join(f"`{t}`" for t in tags.get(rid, [])) or "**NOT VERIFIED**"
        lines.append(f"| {rid} | {r['text']} | {method_name[r['method']]} | {r['source']} | {by} |")
    lines.append("")
    return "\n".join(lines), unverified, unknown


def run(root="."):
    root = pathlib.Path(root)
    reqs = read_requirements(root / "docs" / "02-Requirements.md")
    tags = read_tags(root / "tests")
    md, unverified, unknown = build(reqs, tags)
    (root / "docs" / "RTM.md").write_text(md, encoding="utf-8")
    return reqs, unverified, unknown
